services:
  db:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'diet-api'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
    - "3306:3306"
    expose:
      - '3306'
    volumes:
      - C:/Users/eduar/OneDrive/Documentos/Code/Daily-Diet-API/mysql:/var/lib/mysql